const wordsData = [

    // --- PRONOUNS ---
    { en: "He", fr: "Il", type: "Pronoun" },
    { en: "I", fr: "Je", type: "Pronoun" },
    { en: "It", fr: "Il/Elle", type: "Pronoun" },
    { en: "She", fr: "Elle", type: "Pronoun" },
    { en: "That", fr: "Cela", type: "Pronoun" },
    { en: "These", fr: "Ceux-ci", type: "Pronoun" },
    { en: "They", fr: "Ils/Elles", type: "Pronoun" },
    { en: "This", fr: "Ceci", type: "Pronoun" },
    { en: "Those", fr: "Ceux-là", type: "Pronoun" },
    { en: "We", fr: "Nous", type: "Pronoun" },
    { en: "You", fr: "Tu/Vous", type: "Pronoun" },

    // --- NOUNS ---
    { en: "Actor", fr: "Acteur", type: "Noun" },
    { en: "Actress", fr: "Actrice", type: "Noun" },
    { en: "Afternoon", fr: "Après-midi", type: "Noun" },
    { en: "Air", fr: "Air", type: "Noun" },
    { en: "Airplane", fr: "Avion", type: "Noun" },
    { en: "Airport", fr: "Aéroport", type: "Noun" },
    { en: "Album", fr: "Album", type: "Noun" },
    { en: "Algorithm", fr: "Algorithme", type: "Noun" },
    { en: "Animal", fr: "Animal", type: "Noun" },
    { en: "Anniversary", fr: "Anniversaire", type: "Noun" },
    { en: "Answer", fr: "Réponse", type: "Noun" },
    { en: "Anthem", fr: "Hymne", type: "Noun" },
    { en: "Apple", fr: "Pomme", type: "Noun" },
    { en: "Application", fr: "Application", type: "Noun" },
    { en: "Arm", fr: "Bras", type: "Noun" },
    { en: "Army", fr: "Armée", type: "Noun" },
    { en: "Art", fr: "Art", type: "Noun" },
    { en: "Artifact", fr: "Artefact", type: "Noun" },
    { en: "Asteroid", fr: "Astéroïde", type: "Noun" },
    { en: "Astronaut", fr: "Astronaute", type: "Noun" },
    { en: "Atom", fr: "Atome", type: "Noun" },
    { en: "Attack", fr: "Attaque", type: "Noun" },
    { en: "Attic", fr: "Grenier", type: "Noun" },
    { en: "Audience", fr: "Public", type: "Noun" },
    { en: "Audio", fr: "Audio", type: "Noun" },
    { en: "Author", fr: "Auteur", type: "Noun" },
    { en: "Autumn", fr: "Automne", type: "Noun" },
    { en: "Axle", fr: "Essieu", type: "Noun" },
    { en: "Back", fr: "Dos", type: "Noun" },
    { en: "Backdrop", fr: "Décor", type: "Noun" },
    { en: "Backpack", fr: "Sac à dos", type: "Noun" },
    { en: "Backup", fr: "Sauvegarde", type: "Noun" },
    { en: "Bag", fr: "Sac", type: "Noun" },
    { en: "Balcony", fr: "Balcon", type: "Noun" },
    { en: "Ball", fr: "Balle", type: "Noun" },
    { en: "Ballad", fr: "Ballade", type: "Noun" },
    { en: "Banana", fr: "Banane", type: "Noun" },
    { en: "Bank", fr: "Banque", type: "Noun" },
    { en: "Bank account", fr: "Compte bancaire", type: "Noun" },
    { en: "Barn", fr: "Grange", type: "Noun" },
    { en: "Basement", fr: "Sous-sol", type: "Noun" },
    { en: "Bathroom", fr: "Salle de bain", type: "Noun" },
    { en: "Battery", fr: "Batterie", type: "Noun" },
    { en: "Beach", fr: "Plage", type: "Noun" },
    { en: "Bed", fr: "Lit", type: "Noun" },
    { en: "Bedroom", fr: "Chambre", type: "Noun" },
    { en: "Beer", fr: "Bière", type: "Noun" },
    { en: "Belt", fr: "Ceinture", type: "Noun" },
    { en: "Bill", fr: "Addition", type: "Noun" },
    { en: "Binder", fr: "Classeur", type: "Noun" },
    { en: "Bird", fr: "Oiseau", type: "Noun" },
    { en: "Birthday", fr: "Anniversaire", type: "Noun" },
    { en: "Blood", fr: "Sang", type: "Noun" },
    { en: "Body", fr: "Corps", type: "Noun" },
    { en: "Bone", fr: "Os", type: "Noun" },
    { en: "Bonus Room", fr: "Pièce polyvalente", type: "Noun" },
    { en: "Book", fr: "Livre", type: "Noun" },
    { en: "Boss", fr: "Patron", type: "Noun" },
    { en: "Box", fr: "Boîte", type: "Noun" },
    { en: "Boy", fr: "Garçon", type: "Noun" },
    { en: "Brain", fr: "Cerveau", type: "Noun" },
    { en: "Breach", fr: "Fuite", type: "Noun" },
    { en: "Bread", fr: "Pain", type: "Noun" },
    { en: "Breakfast", fr: "Petit déjeuner", type: "Noun" },
    { en: "Bridge", fr: "Pont", type: "Noun" },
    { en: "Bright windows", fr: "Fenêtres lumineuses", type: "Noun" },
    { en: "Bronze", fr: "Bronze", type: "Noun" },
    { en: "Brother", fr: "Frère", type: "Noun" },
    { en: "Brush", fr: "Pinceau", type: "Noun" },
    { en: "Bus", fr: "Bus", type: "Noun" },
    { en: "Butler's Pantry", fr: "Office", type: "Noun" },
    { en: "Café", fr: "Café", type: "Noun" },
    { en: "Calculator", fr: "Calculatrice", type: "Noun" },
    { en: "Call", fr: "Appel", type: "Noun" },
    { en: "Camera", fr: "Caméra", type: "Noun" },
    { en: "Canvas", fr: "Toile", type: "Noun" },
    { en: "Canyon", fr: "Canyon", type: "Noun" },
    { en: "Capital", fr: "Capitale", type: "Noun" },
    { en: "Car", fr: "Voiture", type: "Noun" },
    { en: "Cargo", fr: "Cargaison", type: "Noun" },
    { en: "Cat", fr: "Chat", type: "Noun" },
    { en: "Cave", fr: "Grotte", type: "Noun" },
    { en: "Celebration", fr: "Célébration", type: "Noun" },
    { en: "Ceremony", fr: "Cérémonie", type: "Noun" },
    { en: "Chair", fr: "Chaise", type: "Noun" },
    { en: "Chalk", fr: "Craie", type: "Noun" },
    { en: "Chance", fr: "Chance", type: "Noun" },
    { en: "Chapter", fr: "Chapitre", type: "Noun" },
    { en: "Cheese", fr: "Fromage", type: "Noun" },
    { en: "Chicken", fr: "Poulet", type: "Noun" },
    { en: "Child", fr: "Enfant", type: "Noun" },
    { en: "Choice", fr: "Choix", type: "Noun" },
    { en: "Choir", fr: "Chorale", type: "Noun" },
    { en: "Circuit", fr: "Circuit", type: "Noun" },
    { en: "City", fr: "Ville", type: "Noun" },
    { en: "Clay", fr: "Argile", type: "Noun" },
    { en: "Cliff", fr: "Falaise", type: "Noun" },
    { en: "Clock", fr: "Horloge", type: "Noun" },
    { en: "Closet", fr: "Placard", type: "Noun" },
    { en: "Cloud", fr: "Nuage", type: "Noun" },
    { en: "Coach", fr: "Entraîneur", type: "Noun" },
    { en: "Coast", fr: "Côte", type: "Noun" },
    { en: "Coat", fr: "Manteau", type: "Noun" },
    { en: "Code", fr: "Code", type: "Noun" },
    { en: "Coffee", fr: "Café", type: "Noun" },
    { en: "Coin", fr: "Pièce", type: "Noun" },
    { en: "Collector", fr: "Collectionneur", type: "Noun" },
    { en: "Comedy", fr: "Comédie", type: "Noun" },
    { en: "Comet", fr: "Comète", type: "Noun" },
    { en: "Company", fr: "Entreprise", type: "Noun" },
    { en: "Compass", fr: "Boussole", type: "Noun" },
    { en: "Composer", fr: "Compositeur", type: "Noun" },
    { en: "Computer", fr: "Ordinateur", type: "Noun" },
    { en: "Concert", fr: "Concert", type: "Noun" },
    { en: "Conductor", fr: "Conducteur", type: "Noun" },
    { en: "Conservatory", fr: "Jardin d'hiver", type: "Noun" },
    { en: "Conversation", fr: "Conversation", type: "Noun" },
    { en: "Corn", fr: "Maïs", type: "Noun" },
    { en: "Cosmos", fr: "Cosmos", type: "Noun" },
    { en: "Costume", fr: "Costume", type: "Noun" },
    { en: "Country", fr: "Pays", type: "Noun" },
    { en: "Court", fr: "Tribunal", type: "Noun" },
    { en: "Cozy fireplace", fr: "Cheminée confortable", type: "Noun" },
    { en: "Crane", fr: "Grue", type: "Noun" },
    { en: "Credit card", fr: "Carte de crédit", type: "Noun" },
    { en: "Critic", fr: "Critique", type: "Noun" },
    { en: "Culture", fr: "Culture", type: "Noun" },
    { en: "Current", fr: "Courant", type: "Noun" },
    { en: "Curtain", fr: "Rideau", type: "Noun" },
    { en: "Dance", fr: "Danse", type: "Noun" },
    { en: "Database", fr: "Base de données", type: "Noun" },
    { en: "Day", fr: "Jour", type: "Noun" },
    { en: "Death", fr: "Mort", type: "Noun" },
    { en: "Decision", fr: "Décision", type: "Noun" },
    { en: "Delivery", fr: "Livraison", type: "Noun" },
    { en: "Den", fr: "Petit salon", type: "Noun" },
    { en: "Desert", fr: "Désert", type: "Noun" },
    { en: "Desk", fr: "Bureau", type: "Noun" },
    { en: "Dialogue", fr: "Dialogue", type: "Noun" },
    { en: "Diesel", fr: "Diesel", type: "Noun" },
    { en: "Dining Room", fr: "Salle à manger", type: "Noun" },
    { en: "Dinner", fr: "Dîner", type: "Noun" },
    { en: "Discovery", fr: "Découverte", type: "Noun" },
    { en: "Dock", fr: "Quai", type: "Noun" },
    { en: "Doctor", fr: "Médecin", type: "Noun" },
    { en: "Dog", fr: "Chien", type: "Noun" },
    { en: "Door", fr: "Porte", type: "Noun" },
    { en: "Drama", fr: "Drame", type: "Noun" },
    { en: "Dream", fr: "Rêve", type: "Noun" },
    { en: "Dress", fr: "Robe", type: "Noun" },
    { en: "Duty", fr: "Devoir", type: "Noun" },
    { en: "Ear", fr: "Oreille", type: "Noun" },
    { en: "Earth", fr: "Terre", type: "Noun" },
    { en: "Easel", fr: "Chevalet", type: "Noun" },
    { en: "Egg", fr: "Oeuf", type: "Noun" },
    { en: "Election", fr: "Élection", type: "Noun" },
    { en: "Electricity", fr: "Électricité", type: "Noun" },
    { en: "Email", fr: "E-mail", type: "Noun" },
    { en: "Employee", fr: "Employé", type: "Noun" },
    { en: "Encryption", fr: "Chiffrement", type: "Noun" },
    { en: "Energy", fr: "Énergie", type: "Noun" },
    { en: "Engine", fr: "Moteur", type: "Noun" },
    { en: "Engineer", fr: "Ingénieur du son", type: "Noun" },
    { en: "Eraser", fr: "Gomme", type: "Noun" },
    { en: "Error", fr: "Erreur", type: "Noun" },
    { en: "Evening", fr: "Soir", type: "Noun" },
    { en: "Exclusive gated community", fr: "Résidence fermée exclusive", type: "Noun" },
    { en: "Exercise Room", fr: "Salle de sport", type: "Noun" },
    { en: "Exhibit", fr: "Exposition", type: "Noun" },
    { en: "Experiment", fr: "Expérience", type: "Noun" },
    { en: "Eye", fr: "Oeil", type: "Noun" },
    { en: "Face", fr: "Visage", type: "Noun" },
    { en: "Family", fr: "Famille", type: "Noun" },
    { en: "Family Room", fr: "Salle de séjour", type: "Noun" },
    { en: "Family-friendly space", fr: "Espace convivial", type: "Noun" },
    { en: "Father", fr: "Père", type: "Noun" },
    { en: "Fear", fr: "Peur", type: "Noun" },
    { en: "Fence", fr: "Clôture", type: "Noun" },
    { en: "Festival", fr: "Festival", type: "Noun" },
    { en: "File", fr: "Fichier", type: "Noun" },
    { en: "Finger", fr: "Doigt", type: "Noun" },
    { en: "Fire", fr: "Feu", type: "Noun" },
    { en: "Firewall", fr: "Pare-feu", type: "Noun" },
    { en: "Fireworks", fr: "Feux d’artifice", type: "Noun" },
    { en: "Fish", fr: "Poisson", type: "Noun" },
    { en: "Floor", fr: "Sol", type: "Noun" },
    { en: "Flower", fr: "Fleur", type: "Noun" },
    { en: "Folder", fr: "Dossier", type: "Noun" },
    { en: "Food", fr: "Nourriture", type: "Noun" },
    { en: "Foot", fr: "Pied", type: "Noun" },
    { en: "Forest", fr: "Forêt", type: "Noun" },
    { en: "Forklift", fr: "Chariot élévateur", type: "Noun" },
    { en: "Foyer", fr: "Hall d'entrée", type: "Noun" },
    { en: "Freedom", fr: "Liberté", type: "Noun" },
    { en: "Freight", fr: "Fret", type: "Noun" },
    { en: "Friend", fr: "Ami", type: "Noun" },
    { en: "Fruit", fr: "Fruit", type: "Noun" },
    { en: "Fuel", fr: "Carburant", type: "Noun" },
    { en: "Functional built-in shelves", fr: "Étagères intégrées fonctionnelles", type: "Noun" },
    { en: "Future", fr: "Avenir", type: "Noun" },
    { en: "Galaxy", fr: "Galaxie", type: "Noun" },
    { en: "Gallery", fr: "Galerie", type: "Noun" },
    { en: "Game", fr: "Jeu", type: "Noun" },
    { en: "Game Room", fr: "Salle de jeux", type: "Noun" },
    { en: "Garage", fr: "Garage", type: "Noun" },
    { en: "Garden", fr: "Jardin", type: "Noun" },
    { en: "Gasoline", fr: "Essence", type: "Noun" },
    { en: "Gear", fr: "Engrenage", type: "Noun" },
    { en: "Generator", fr: "Générateur", type: "Noun" },
    { en: "Genre", fr: "Genre", type: "Noun" },
    { en: "Geyser", fr: "Geyser", type: "Noun" },
    { en: "Gift", fr: "Cadeau", type: "Noun" },
    { en: "Girl", fr: "Fille", type: "Noun" },
    { en: "Glacier", fr: "Glacier", type: "Noun" },
    { en: "Glasses", fr: "Lunettes", type: "Noun" },
    { en: "Gloves", fr: "Gants", type: "Noun" },
    { en: "Goal", fr: "Objectif", type: "Noun" },
    { en: "Government", fr: "Gouvernement", type: "Noun" },
    { en: "Grass", fr: "Herbe", type: "Noun" },
    { en: "Gravity", fr: "Gravité", type: "Noun" },
    { en: "Guest", fr: "Invité", type: "Noun" },
    { en: "Guest Room", fr: "Chambre d'amis", type: "Noun" },
    { en: "Guide", fr: "Guide", type: "Noun" },
    { en: "Hair", fr: "Cheveux", type: "Noun" },
    { en: "Hand", fr: "Main", type: "Noun" },
    { en: "Happiness", fr: "Bonheur", type: "Noun" },
    { en: "Hardware", fr: "Matériel", type: "Noun" },
    { en: "Harvest", fr: "Récolte", type: "Noun" },
    { en: "Hat", fr: "Chapeau", type: "Noun" },
    { en: "Hate", fr: "Haine", type: "Noun" },
    { en: "Hay", fr: "Foin", type: "Noun" },
    { en: "Head", fr: "Tête", type: "Noun" },
    { en: "Headphones", fr: "Écouteurs", type: "Noun" },
    { en: "Health", fr: "Santé", type: "Noun" },
    { en: "Heart", fr: "Coeur", type: "Noun" },
    { en: "High ceilings", fr: "Hauts plafonds", type: "Noun" },
    { en: "Highlighter", fr: "Surligneur", type: "Noun" },
    { en: "Historic district", fr: "Quartier historique", type: "Noun" },
    { en: "History", fr: "Histoire", type: "Noun" },
    { en: "Holiday", fr: "Vacances", type: "Noun" },
    { en: "Home", fr: "Domicile", type: "Noun" },
    { en: "Home Gym", fr: "Gym à domicile", type: "Noun" },
    { en: "Hospital", fr: "Hôpital", type: "Noun" },
    { en: "Hotel", fr: "Hôtel", type: "Noun" },
    { en: "Hour", fr: "Heure", type: "Noun" },
    { en: "House", fr: "Maison", type: "Noun" },
    { en: "Hub", fr: "Plateforme", type: "Noun" },
    { en: "Human", fr: "Humain", type: "Noun" },
    { en: "Idea", fr: "Idée", type: "Noun" },
    { en: "In-law Suite", fr: "Suite indépendante", type: "Noun" },
    { en: "Information", fr: "Information", type: "Noun" },
    { en: "Ink", fr: "Encre", type: "Noun" },
    { en: "Itinerary", fr: "Itinéraire", type: "Noun" },
    { en: "Jacket", fr: "Veste", type: "Noun" },
    { en: "Job", fr: "Travail", type: "Noun" },
    { en: "Justice", fr: "Justice", type: "Noun" },
    { en: "Key", fr: "Clé", type: "Noun" },
    { en: "Keyboard", fr: "Clavier", type: "Noun" },
    { en: "King", fr: "Roi", type: "Noun" },
    { en: "Kitchen", fr: "Cuisine", type: "Noun" },
    { en: "Knowledge", fr: "Connaissance", type: "Noun" },
    { en: "Lagoon", fr: "Lagon", type: "Noun" },
    { en: "Lamp", fr: "Lampe", type: "Noun" },
    { en: "Landmark", fr: "Point de repère", type: "Noun" },
    { en: "Landscape", fr: "Paysage", type: "Noun" },
    { en: "Language", fr: "Langue", type: "Noun" },
    { en: "Launch", fr: "Lancement", type: "Noun" },
    { en: "Laundry Room", fr: "Buanderie", type: "Noun" },
    { en: "Law", fr: "Loi", type: "Noun" },
    { en: "Leg", fr: "Jambe", type: "Noun" },
    { en: "Letter", fr: "Lettre", type: "Noun" },
    { en: "Lever", fr: "Levier", type: "Noun" },
    { en: "Library", fr: "Bibliothèque", type: "Noun" },
    { en: "Lie", fr: "Mensonge", type: "Noun" },
    { en: "Life", fr: "Vie", type: "Noun" },
    { en: "Living Room", fr: "Salon", type: "Noun" },
    { en: "Love", fr: "Amour", type: "Noun" },
    { en: "Luck", fr: "Fortune", type: "Noun" },
    { en: "Luggage", fr: "Bagage", type: "Noun" },
    { en: "Lunch", fr: "Déjeuner", type: "Noun" },
    { en: "Machine", fr: "Machine", type: "Noun" },
    { en: "Man", fr: "Homme", type: "Noun" },
    { en: "Map", fr: "Carte", type: "Noun" },
    { en: "Marble", fr: "Marbre", type: "Noun" },
    { en: "Marker", fr: "Marqueur", type: "Noun" },
    { en: "Market", fr: "Marché", type: "Noun" },
    { en: "Mask", fr: "Masque", type: "Noun" },
    { en: "Master Bedroom", fr: "Chambre principale", type: "Noun" },
    { en: "Match", fr: "Match", type: "Noun" },
    { en: "Meadow", fr: "Prairie", type: "Noun" },
    { en: "Meat", fr: "Viande", type: "Noun" },
    { en: "Medicine", fr: "Médicament", type: "Noun" },
    { en: "Meeting", fr: "Réunion", type: "Noun" },
    { en: "Melody", fr: "Mélodie", type: "Noun" },
    { en: "Menu", fr: "Menu", type: "Noun" },
    { en: "Message", fr: "Message", type: "Noun" },
    { en: "Meteor", fr: "Météore", type: "Noun" },
    { en: "Microphone", fr: "Microphone", type: "Noun" },
    { en: "Milk", fr: "Lait", type: "Noun" },
    { en: "Minute", fr: "Minute", type: "Noun" },
    { en: "Mirror", fr: "Miroir", type: "Noun" },
    { en: "Mission", fr: "Mission", type: "Noun" },
    { en: "Mix", fr: "Mix", type: "Noun" },
    { en: "Module", fr: "Module", type: "Noun" },
    { en: "Money", fr: "Argent", type: "Noun" },
    { en: "Monitor", fr: "Écran", type: "Noun" },
    { en: "Month", fr: "Mois", type: "Noun" },
    { en: "Monument", fr: "Monument", type: "Noun" },
    { en: "Moon", fr: "Lune", type: "Noun" },
    { en: "Morning", fr: "Matin", type: "Noun" },
    { en: "Mother", fr: "Mère", type: "Noun" },
    { en: "Motor", fr: "Moteur", type: "Noun" },
    { en: "Mountain", fr: "Montagne", type: "Noun" },
    { en: "Mouse", fr: "Souris", type: "Noun" },
    { en: "Mouth", fr: "Bouche", type: "Noun" },
    { en: "Movie", fr: "Film", type: "Noun" },
    { en: "Mudroom", fr: "Vestibule", type: "Noun" },
    { en: "Mural", fr: "Fresque", type: "Noun" },
    { en: "Museum", fr: "Musée", type: "Noun" },
    { en: "Music", fr: "Musique", type: "Noun" },
    { en: "Name", fr: "Nom", type: "Noun" },
    { en: "Nation", fr: "Nation", type: "Noun" },
    { en: "Necklace", fr: "Collier", type: "Noun" },
    { en: "Neighbor", fr: "Voisin", type: "Noun" },
    { en: "Neighborhood", fr: "Quartier", type: "Noun" },
    { en: "Network", fr: "Réseau", type: "Noun" },
    { en: "Night", fr: "Nuit", type: "Noun" },
    { en: "Noise", fr: "Bruit", type: "Noun" },
    { en: "Nose", fr: "Nez", type: "Noun" },
    { en: "Note", fr: "Note", type: "Noun" },
    { en: "Notebook", fr: "Carnet", type: "Noun" },
    { en: "Novel", fr: "Roman", type: "Noun" },
    { en: "Number", fr: "Nombre", type: "Noun" },
    { en: "Nurse", fr: "Infirmière", type: "Noun" },
    { en: "Nursery", fr: "Chambre de bébé", type: "Noun" },
    { en: "Ocean", fr: "Océan", type: "Noun" },
    { en: "Office", fr: "Bureau", type: "Noun" },
    { en: "Orbit", fr: "Orbite", type: "Noun" },
    { en: "Orchard", fr: "Verger", type: "Noun" },
    { en: "Orchestra", fr: "Orchestre", type: "Noun" },
    { en: "Painting", fr: "Peinture", type: "Noun" },
    { en: "Palette", fr: "Palette", type: "Noun" },
    { en: "Pantry", fr: "Garde-manger", type: "Noun" },
    { en: "Pants", fr: "Pantalon", type: "Noun" },
    { en: "Paper", fr: "Papier", type: "Noun" },
    { en: "Parade", fr: "Défilé", type: "Noun" },
    { en: "Paragraph", fr: "Paragraphe", type: "Noun" },
    { en: "Park", fr: "Parc", type: "Noun" },
    { en: "Party", fr: "Fête", type: "Noun" },
    { en: "Passport", fr: "Passeport", type: "Noun" },
    { en: "Password", fr: "Mot de passe", type: "Noun" },
    { en: "Past", fr: "Passé", type: "Noun" },
    { en: "Patio", fr: "Patio", type: "Noun" },
    { en: "Payment", fr: "Paiement", type: "Noun" },
    { en: "Pen", fr: "Stylo", type: "Noun" },
    { en: "Pencil", fr: "Crayon", type: "Noun" },
    { en: "Pepper", fr: "Poivre", type: "Noun" },
    { en: "Person", fr: "Personne", type: "Noun" },
    { en: "Phone", fr: "Téléphone", type: "Noun" },
    { en: "Photo", fr: "Photo", type: "Noun" },
    { en: "Photograph", fr: "Photographie", type: "Noun" },
    { en: "Planet", fr: "Planète", type: "Noun" },
    { en: "Plate", fr: "Assiette", type: "Noun" },
    { en: "Plateau", fr: "Plateau", type: "Noun" },
    { en: "Platform", fr: "Plateforme", type: "Noun" },
    { en: "Player", fr: "Joueur", type: "Noun" },
    { en: "Poem", fr: "Poème", type: "Noun" },
    { en: "Poet", fr: "Poète", type: "Noun" },
    { en: "Police", fr: "Police", type: "Noun" },
    { en: "Porch", fr: "Porche", type: "Noun" },
    { en: "Portrait", fr: "Portrait", type: "Noun" },
    { en: "Potato", fr: "Pomme de terre", type: "Noun" },
    { en: "Present", fr: "Présent", type: "Noun" },
    { en: "Price", fr: "Prix", type: "Noun" },
    { en: "Primary Bathroom", fr: "Salle de bain principale", type: "Noun" },
    { en: "Primary Bedroom", fr: "Chambre principale", type: "Noun" },
    { en: "Printer", fr: "Imprimante", type: "Noun" },
    { en: "Problem", fr: "Problème", type: "Noun" },
    { en: "Producer", fr: "Producteur", type: "Noun" },
    { en: "Program", fr: "Programme", type: "Noun" },
    { en: "Project", fr: "Projet", type: "Noun" },
    { en: "Prop", fr: "Accessoire", type: "Noun" },
    { en: "Pumpkin", fr: "Citrouille", type: "Noun" },
    { en: "Queen", fr: "Reine", type: "Noun" },
    { en: "Question", fr: "Question", type: "Noun" },
    { en: "Race", fr: "Course", type: "Noun" },
    { en: "Rain", fr: "Pluie", type: "Noun" },
    { en: "Recording", fr: "Enregistrement", type: "Noun" },
    { en: "Recreation Room", fr: "Salle de loisirs", type: "Noun" },
    { en: "Reef", fr: "Récif", type: "Noun" },
    { en: "Relaxing color scheme", fr: "Palette de couleurs relaxante", type: "Noun" },
    { en: "Research", fr: "Recherche", type: "Noun" },
    { en: "Restaurant", fr: "Restaurant", type: "Noun" },
    { en: "Rhythm", fr: "Rythme", type: "Noun" },
    { en: "Right", fr: "Droit", type: "Noun" },
    { en: "Rights", fr: "Droits", type: "Noun" },
    { en: "Ring", fr: "Bague", type: "Noun" },
    { en: "Ritual", fr: "Rituel", type: "Noun" },
    { en: "River", fr: "Rivière", type: "Noun" },
    { en: "Road", fr: "Route", type: "Noun" },
    { en: "Rocket", fr: "Fusée", type: "Noun" },
    { en: "Roof", fr: "Toit", type: "Noun" },
    { en: "Room", fr: "Pièce", type: "Noun" },
    { en: "Router", fr: "Routeur", type: "Noun" },
    { en: "Rule", fr: "Règle", type: "Noun" },
    { en: "Ruler", fr: "Règle", type: "Noun" },
    { en: "Sadness", fr: "Tristesse", type: "Noun" },
    { en: "Salary", fr: "Salaire", type: "Noun" },
    { en: "Salt", fr: "Sel", type: "Noun" },
    { en: "Satellite", fr: "Satellite", type: "Noun" },
    { en: "Scarf", fr: "Écharpe", type: "Noun" },
    { en: "Scene", fr: "Scène", type: "Noun" },
    { en: "Schedule", fr: "Horaire", type: "Noun" },
    { en: "School", fr: "École", type: "Noun" },
    { en: "Science", fr: "Science", type: "Noun" },
    { en: "Screen", fr: "Écran", type: "Noun" },
    { en: "Script", fr: "Scénario", type: "Noun" },
    { en: "Sculptor", fr: "Sculpteur", type: "Noun" },
    { en: "Sculpture", fr: "Sculpture", type: "Noun" },
    { en: "Sea", fr: "Mer", type: "Noun" },
    { en: "Season", fr: "Saison", type: "Noun" },
    { en: "Second", fr: "Seconde", type: "Noun" },
    { en: "Security", fr: "Sécurité", type: "Noun" },
    { en: "Sensor", fr: "Capteur", type: "Noun" },
    { en: "Sentence", fr: "Phrase", type: "Noun" },
    { en: "Server", fr: "Serveur", type: "Noun" },
    { en: "Shipment", fr: "Expédition", type: "Noun" },
    { en: "Shirt", fr: "Chemise", type: "Noun" },
    { en: "Shoe", fr: "Chaussure", type: "Noun" },
    { en: "Shoes", fr: "Chaussures", type: "Noun" },
    { en: "Shore", fr: "Rivage", type: "Noun" },
    { en: "Signal", fr: "Signal", type: "Noun" },
    { en: "Silence", fr: "Silence", type: "Noun" },
    { en: "Silo", fr: "Silo", type: "Noun" },
    { en: "Sister", fr: "Soeur", type: "Noun" },
    { en: "Skin", fr: "Peau", type: "Noun" },
    { en: "Skirt", fr: "Jupe", type: "Noun" },
    { en: "Sky", fr: "Ciel", type: "Noun" },
    { en: "Sleek modern design", fr: "Design moderne et élégant", type: "Noun" },
    { en: "Snow", fr: "Neige", type: "Noun" },
    { en: "Sock", fr: "Chaussette", type: "Noun" },
    { en: "Software", fr: "Logiciel", type: "Noun" },
    { en: "Soil", fr: "Sol", type: "Noun" },
    { en: "Solution", fr: "Solution", type: "Noun" },
    { en: "Song", fr: "Chanson", type: "Noun" },
    { en: "Space", fr: "Espace", type: "Noun" },
    { en: "Spaceship", fr: "Vaisseau spatial", type: "Noun" },
    { en: "Speaker", fr: "Haut-parleur", type: "Noun" },
    { en: "Sport", fr: "Sport", type: "Noun" },
    { en: "Spotlight", fr: "Projecteur", type: "Noun" },
    { en: "Spring", fr: "Printemps", type: "Noun" },
    { en: "Square", fr: "Place", type: "Noun" },
    { en: "Stadium", fr: "Stade", type: "Noun" },
    { en: "Stage", fr: "Scène", type: "Noun" },
    { en: "Stagehand", fr: "Machiniste", type: "Noun" },
    { en: "Star", fr: "Étoile", type: "Noun" },
    { en: "Stomach", fr: "Ventre", type: "Noun" },
    { en: "Storage", fr: "Stockage", type: "Noun" },
    { en: "Storage Room", fr: "Débarras", type: "Noun" },
    { en: "Store", fr: "Magasin", type: "Noun" },
    { en: "Storm", fr: "Tempête", type: "Noun" },
    { en: "Street", fr: "Rue", type: "Noun" },
    { en: "Student", fr: "Étudiant", type: "Noun" },
    { en: "Studio", fr: "Studio", type: "Noun" },
    { en: "Study", fr: "Cabinet de travail", type: "Noun" },
    { en: "Sugar", fr: "Sucre", type: "Noun" },
    { en: "Summer", fr: "Été", type: "Noun" },
    { en: "Sun", fr: "Soleil", type: "Noun" },
    { en: "Sunroom", fr: "Véranda", type: "Noun" },
    { en: "Swamp", fr: "Marais", type: "Noun" },
    { en: "Symphony", fr: "Symphonie", type: "Noun" },
    { en: "Table", fr: "Table", type: "Noun" },
    { en: "Tax", fr: "Impôt", type: "Noun" },
    { en: "Tea", fr: "Thé", type: "Noun" },
    { en: "Teacher", fr: "Professeur", type: "Noun" },
    { en: "Team", fr: "Équipe", type: "Noun" },
    { en: "Telescope", fr: "Télescope", type: "Noun" },
    { en: "Tempo", fr: "Tempo", type: "Noun" },
    { en: "Theater", fr: "Théâtre", type: "Noun" },
    { en: "Ticket", fr: "Billet", type: "Noun" },
    { en: "Time", fr: "Temps", type: "Noun" },
    { en: "Tomato", fr: "Tomate", type: "Noun" },
    { en: "Tool", fr: "Outil", type: "Noun" },
    { en: "Tooth", fr: "Dent", type: "Noun" },
    { en: "Tour", fr: "Visite", type: "Noun" },
    { en: "Tournament", fr: "Tournoi", type: "Noun" },
    { en: "Toy", fr: "Jouet", type: "Noun" },
    { en: "Track", fr: "Piste", type: "Noun" },
    { en: "Tractor", fr: "Tracteur", type: "Noun" },
    { en: "Tradition", fr: "Tradition", type: "Noun" },
    { en: "Train", fr: "Train", type: "Noun" },
    { en: "Transit", fr: "Transit", type: "Noun" },
    { en: "Translation", fr: "Traduction", type: "Noun" },
    { en: "Transmission", fr: "Transmission", type: "Noun" },
    { en: "Tree", fr: "Arbre", type: "Noun" },
    { en: "Truth", fr: "Vérité", type: "Noun" },
    { en: "Tundra", fr: "Toundra", type: "Noun" },
    { en: "Tune", fr: "Air", type: "Noun" },
    { en: "Turbine", fr: "Turbine", type: "Noun" },
    { en: "Umbrella", fr: "Parapluie", type: "Noun" },
    { en: "Universe", fr: "Univers", type: "Noun" },
    { en: "University", fr: "Université", type: "Noun" },
    { en: "Valley", fr: "Vallée", type: "Noun" },
    { en: "Vaulted ceilings", fr: "Plafonds voûtés", type: "Noun" },
    { en: "Vegetable", fr: "Légume", type: "Noun" },
    { en: "Victory", fr: "Victoire", type: "Noun" },
    { en: "Village", fr: "Village", type: "Noun" },
    { en: "Vineyard", fr: "Vignoble", type: "Noun" },
    { en: "Virus", fr: "Virus", type: "Noun" },
    { en: "Voice", fr: "Voix", type: "Noun" },
    { en: "Volcano", fr: "Volcan", type: "Noun" },
    { en: "Voltage", fr: "Tension", type: "Noun" },
    { en: "Walk-in Closet", fr: "Dressing", type: "Noun" },
    { en: "Wall", fr: "Mur", type: "Noun" },
    { en: "Wallet", fr: "Portefeuille", type: "Noun" },
    { en: "Warehouse", fr: "Entrepôt", type: "Noun" },
    { en: "Warm hardwood floors", fr: "Parquets chaleureux", type: "Noun" },
    { en: "Watch", fr: "Montre", type: "Noun" },
    { en: "Water", fr: "Eau", type: "Noun" },
    { en: "Waterfall", fr: "Cascade", type: "Noun" },
    { en: "Waterfront", fr: "Bord de l'eau", type: "Noun" },
    { en: "Way", fr: "Chemin", type: "Noun" },
    { en: "Weather", fr: "Météo", type: "Noun" },
    { en: "Wedding", fr: "Mariage", type: "Noun" },
    { en: "Week", fr: "Semaine", type: "Noun" },
    { en: "Welcoming atmosphere", fr: "Atmosphère accueillante", type: "Noun" },
    { en: "Well-appointed entertainment center", fr: "Centre de divertissement bien équipé", type: "Noun" },
    { en: "Wheat", fr: "Blé", type: "Noun" },
    { en: "Wheel", fr: "Roue", type: "Noun" },
    { en: "Wind", fr: "Vent", type: "Noun" },
    { en: "Window", fr: "Fenêtre", type: "Noun" },
    { en: "Wine", fr: "Vin", type: "Noun" },
    { en: "Winter", fr: "Hiver", type: "Noun" },
    { en: "Woman", fr: "Femme", type: "Noun" },
    { en: "Word", fr: "Mot", type: "Noun" },
    { en: "Work", fr: "Travail", type: "Noun" },
    { en: "Workshop", fr: "Atelier", type: "Noun" },
    { en: "World", fr: "Monde", type: "Noun" },
    { en: "Year", fr: "Année", type: "Noun" },

    // --- VERBS ---
    { en: "Is", fr: "Est", type: "Verb" },
    { en: "To Answer", fr: "Répondre", type: "Verb" },
    { en: "To Arrive", fr: "Arriver", type: "Verb" },
    { en: "To Ask", fr: "Demander", type: "Verb" },
    { en: "To Be", fr: "Être", type: "Verb" },
    { en: "To Believe", fr: "Croire", type: "Verb" },
    { en: "To Break", fr: "Casser", type: "Verb" },
    { en: "To Build", fr: "Construire", type: "Verb" },
    { en: "To Buy", fr: "Acheter", type: "Verb" },
    { en: "To Call", fr: "Appeler", type: "Verb" },
    { en: "To Change", fr: "Changer", type: "Verb" },
    { en: "To Clean", fr: "Nettoyer", type: "Verb" },
    { en: "To Close", fr: "Fermer", type: "Verb" },
    { en: "To Come", fr: "Venir", type: "Verb" },
    { en: "To Cook", fr: "Cuisiner", type: "Verb" },
    { en: "To Cost", fr: "Coûter", type: "Verb" },
    { en: "To Cut", fr: "Couper", type: "Verb" },
    { en: "To Die", fr: "Mourir", type: "Verb" },
    { en: "To Do", fr: "Faire", type: "Verb" },
    { en: "To Drink", fr: "Boire", type: "Verb" },
    { en: "To Drive", fr: "Conduire", type: "Verb" },
    { en: "To Eat", fr: "Manger", type: "Verb" },
    { en: "To Enter", fr: "Entrer", type: "Verb" },
    { en: "To Exit", fr: "Sortir", type: "Verb" },
    { en: "To Fall", fr: "Tomber", type: "Verb" },
    { en: "To Fear", fr: "Craindre", type: "Verb" },
    { en: "To Feel", fr: "Sentir", type: "Verb" },
    { en: "To Find", fr: "Trouver", type: "Verb" },
    { en: "To Finish", fr: "Finir", type: "Verb" },
    { en: "To Fix", fr: "Réparer", type: "Verb" },
    { en: "To Fly", fr: "Voler", type: "Verb" },
    { en: "To Forget", fr: "Oublier", type: "Verb" },
    { en: "To Get", fr: "Obtenir", type: "Verb" },
    { en: "To Give", fr: "Donner", type: "Verb" },
    { en: "To Go", fr: "Aller", type: "Verb" },
    { en: "To Grow", fr: "Grandir", type: "Verb" },
    { en: "To Hate", fr: "Détester", type: "Verb" },
    { en: "To Have", fr: "Avoir", type: "Verb" },
    { en: "To Hear", fr: "Entendre", type: "Verb" },
    { en: "To Help", fr: "Aider", type: "Verb" },
    { en: "To Hope", fr: "Espérer", type: "Verb" },
    { en: "To Jump", fr: "Sauter", type: "Verb" },
    { en: "To Know", fr: "Savoir", type: "Verb" },
    { en: "To Learn", fr: "Apprendre", type: "Verb" },
    { en: "To Leave", fr: "Partir", type: "Verb" },
    { en: "To Like", fr: "Aimer", type: "Verb" },
    { en: "To Listen", fr: "Écouter", type: "Verb" },
    { en: "To Live", fr: "Vivre", type: "Verb" },
    { en: "To Look", fr: "Regarder", type: "Verb" },
    { en: "To Lose", fr: "Perdre", type: "Verb" },
    { en: "To Love", fr: "Adorer", type: "Verb" },
    { en: "To Make", fr: "Fabriquer", type: "Verb" },
    { en: "To Move", fr: "Bouger", type: "Verb" },
    { en: "To Need", fr: "Avoir besoin", type: "Verb" },
    { en: "To Open", fr: "Ouvrir", type: "Verb" },
    { en: "To Pay", fr: "Payer", type: "Verb" },
    { en: "To Play", fr: "Jouer", type: "Verb" },
    { en: "To Put", fr: "Mettre", type: "Verb" },
    { en: "To Read", fr: "Lire", type: "Verb" },
    { en: "To Remember", fr: "Se souvenir", type: "Verb" },
    { en: "To Ride", fr: "Monter", type: "Verb" },
    { en: "To Run", fr: "Courir", type: "Verb" },
    { en: "To Save", fr: "Sauver", type: "Verb" },
    { en: "To Say", fr: "Dire", type: "Verb" },
    { en: "To Search", fr: "Chercher", type: "Verb" },
    { en: "To See", fr: "Voir", type: "Verb" },
    { en: "To Sell", fr: "Vendre", type: "Verb" },
    { en: "To Shout", fr: "Crier", type: "Verb" },
    { en: "To Show", fr: "Montrer", type: "Verb" },
    { en: "To Sleep", fr: "Dormir", type: "Verb" },
    { en: "To Speak", fr: "Parler", type: "Verb" },
    { en: "To Spend", fr: "Dépenser", type: "Verb" },
    { en: "To Start", fr: "Commencer", type: "Verb" },
    { en: "To Stay", fr: "Rester", type: "Verb" },
    { en: "To Stop", fr: "Arrêter", type: "Verb" },
    { en: "To Study", fr: "Étudier", type: "Verb" },
    { en: "To Swim", fr: "Nager", type: "Verb" },
    { en: "To Take", fr: "Prendre", type: "Verb" },
    { en: "To Talk", fr: "Discuter", type: "Verb" },
    { en: "To Teach", fr: "Enseigner", type: "Verb" },
    { en: "To Think", fr: "Penser", type: "Verb" },
    { en: "To Try", fr: "Essayer", type: "Verb" },
    { en: "To Understand", fr: "Comprendre", type: "Verb" },
    { en: "To Use", fr: "Utiliser", type: "Verb" },
    { en: "To Wake", fr: "Réveiller", type: "Verb" },
    { en: "To Walk", fr: "Marcher", type: "Verb" },
    { en: "To Want", fr: "Vouloir", type: "Verb" },
    { en: "To Wash", fr: "Laver", type: "Verb" },
    { en: "To Whisper", fr: "Chuchoter", type: "Verb" },
    { en: "To Win", fr: "Gagner", type: "Verb" },
    { en: "To Work", fr: "Travailler", type: "Verb" },
    { en: "To Write", fr: "Écrire", type: "Verb" },
    { en: "Was", fr: "Était", type: "Verb" },
    { en: "Will be", fr: "Sera", type: "Verb" },

    // --- ADJECTIVES ---
    { en: "Airy", fr: "Aéré", type: "Adjective" },
    { en: "Angry", fr: "En colère", type: "Adjective" },
    { en: "Bad", fr: "Mauvais", type: "Adjective" },
    { en: "Beautiful", fr: "Beau", type: "Adjective" },
    { en: "Big", fr: "Grand", type: "Adjective" },
    { en: "Bitter", fr: "Amer", type: "Adjective" },
    { en: "Black", fr: "Noir", type: "Adjective" },
    { en: "Blue", fr: "Bleu", type: "Adjective" },
    { en: "Blunt", fr: "Émoussé", type: "Adjective" },
    { en: "Bored", fr: "Ennuyé", type: "Adjective" },
    { en: "Brave", fr: "Courageux", type: "Adjective" },
    { en: "Breathtaking", fr: "À couper le souffle", type: "Adjective" },
    { en: "Bright", fr: "Lumineux", type: "Adjective" },
    { en: "Brown", fr: "Marron", type: "Adjective" },
    { en: "Busy", fr: "Occupé", type: "Adjective" },
    { en: "Calm", fr: "Calme", type: "Adjective" },
    { en: "Captivating", fr: "Captivant", type: "Adjective" },
    { en: "Centrally located", fr: "Situé au centre", type: "Adjective" },
    { en: "Charming", fr: "Charmant", type: "Adjective" },
    { en: "Clean", fr: "Propre", type: "Adjective" },
    { en: "Cold", fr: "Froid", type: "Adjective" },
    { en: "Colorful", fr: "Coloré", type: "Adjective" },
    { en: "Complex", fr: "Complexe", type: "Adjective" },
    { en: "Confident", fr: "Confiant", type: "Adjective" },
    { en: "Contemporary", fr: "Contemporain", type: "Adjective" },
    { en: "Cool", fr: "Frais", type: "Adjective" },
    { en: "Correct", fr: "Correct", type: "Adjective" },
    { en: "Cozy", fr: "Confortable", type: "Adjective" },
    { en: "Cute", fr: "Mignon", type: "Adjective" },
    { en: "Dangerous", fr: "Dangereux", type: "Adjective" },
    { en: "Dark", fr: "Sombre", type: "Adjective" },
    { en: "Delicious", fr: "Délicieux", type: "Adjective" },
    { en: "Different", fr: "Différent", type: "Adjective" },
    { en: "Difficult", fr: "Difficile", type: "Adjective" },
    { en: "Dirty", fr: "Sale", type: "Adjective" },
    { en: "Disgusting", fr: "Dégoûtant", type: "Adjective" },
    { en: "Dry", fr: "Sec", type: "Adjective" },
    { en: "Dull", fr: "Terne", type: "Adjective" },
    { en: "Easy", fr: "Facile", type: "Adjective" },
    { en: "Elegant", fr: "Élégant", type: "Adjective" },
    { en: "Empty", fr: "Vide", type: "Adjective" },
    { en: "Energetic", fr: "Énergique", type: "Adjective" },
    { en: "Excited", fr: "Excité", type: "Adjective" },
    { en: "Exquisite", fr: "Exquis", type: "Adjective" },
    { en: "False", fr: "Faux", type: "Adjective" },
    { en: "Family-oriented", fr: "Familial", type: "Adjective" },
    { en: "Famous", fr: "Célèbre", type: "Adjective" },
    { en: "Fast", fr: "Rapide", type: "Adjective" },
    { en: "Free", fr: "Libre", type: "Adjective" },
    { en: "Fresh", fr: "Frais", type: "Adjective" },
    { en: "Full", fr: "Plein", type: "Adjective" },
    { en: "Funny", fr: "Drôle", type: "Adjective" },
    { en: "Good", fr: "Bon", type: "Adjective" },
    { en: "Grand", fr: "Grandiose", type: "Adjective" },
    { en: "Green", fr: "Vert", type: "Adjective" },
    { en: "Grey", fr: "Gris", type: "Adjective" },
    { en: "Happy", fr: "Heureux", type: "Adjective" },
    { en: "Hard", fr: "Dur", type: "Adjective" },
    { en: "Healthy", fr: "Sain", type: "Adjective" },
    { en: "Heavy", fr: "Lourd", type: "Adjective" },
    { en: "High", fr: "Haut", type: "Adjective" },
    { en: "Historic", fr: "Historique", type: "Adjective" },
    { en: "Honest", fr: "Honnête", type: "Adjective" },
    { en: "Hot", fr: "Chaud", type: "Adjective" },
    { en: "Immaculate", fr: "Immaculé", type: "Adjective" },
    { en: "Important", fr: "Important", type: "Adjective" },
    { en: "Inviting", fr: "Invitant", type: "Adjective" },
    { en: "Kind", fr: "Gentil", type: "Adjective" },
    { en: "Lazy", fr: "Paresseux", type: "Adjective" },
    { en: "Light", fr: "Léger", type: "Adjective" },
    { en: "Long", fr: "Long", type: "Adjective" },
    { en: "Low", fr: "Bas", type: "Adjective" },
    { en: "Lucky", fr: "Chanceux", type: "Adjective" },
    { en: "Lush", fr: "Luxuriant", type: "Adjective" },
    { en: "Luxurious", fr: "Luxueux", type: "Adjective" },
    { en: "Majestic", fr: "Majestueux", type: "Adjective" },
    { en: "Mean", fr: "Méchant", type: "Adjective" },
    { en: "Modern", fr: "Moderne", type: "Adjective" },
    { en: "Narrow", fr: "Étroit", type: "Adjective" },
    { en: "Necessary", fr: "Nécessaire", type: "Adjective" },
    { en: "New", fr: "Nouveau", type: "Adjective" },
    { en: "Old", fr: "Vieux", type: "Adjective" },
    { en: "Opulent", fr: "Opulent", type: "Adjective" },
    { en: "Orange", fr: "Orange", type: "Adjective" },
    { en: "Peaceful", fr: "Paisible", type: "Adjective" },
    { en: "Picturesque", fr: "Pittoresque", type: "Adjective" },
    { en: "Pink", fr: "Rose", type: "Adjective" },
    { en: "Polite", fr: "Poli", type: "Adjective" },
    { en: "Poor", fr: "Pauvre", type: "Adjective" },
    { en: "Possible", fr: "Possible", type: "Adjective" },
    { en: "Pretty", fr: "Joli", type: "Adjective" },
    { en: "Pristine", fr: "Immaculé", type: "Adjective" },
    { en: "Purple", fr: "Violet", type: "Adjective" },
    { en: "Red", fr: "Rouge", type: "Adjective" },
    { en: "Renovated", fr: "Rénové", type: "Adjective" },
    { en: "Rich", fr: "Riche", type: "Adjective" },
    { en: "Rotten", fr: "Pourri", type: "Adjective" },
    { en: "Rough", fr: "Rugueux", type: "Adjective" },
    { en: "Rude", fr: "Impoli", type: "Adjective" },
    { en: "Rustic", fr: "Rustique", type: "Adjective" },
    { en: "Sad", fr: "Triste", type: "Adjective" },
    { en: "Safe", fr: "Sûr", type: "Adjective" },
    { en: "Salty", fr: "Salé", type: "Adjective" },
    { en: "Same", fr: "Même", type: "Adjective" },
    { en: "Scared", fr: "Effrayé", type: "Adjective" },
    { en: "Secluded", fr: "Isolé", type: "Adjective" },
    { en: "Serene", fr: "Serein", type: "Adjective" },
    { en: "Serious", fr: "Sérieux", type: "Adjective" },
    { en: "Sharp", fr: "Tranchant", type: "Adjective" },
    { en: "Shiny", fr: "Brillant", type: "Adjective" },
    { en: "Short", fr: "Court", type: "Adjective" },
    { en: "Shy", fr: "Timide", type: "Adjective" },
    { en: "Sick", fr: "Malade", type: "Adjective" },
    { en: "Simple", fr: "Simple", type: "Adjective" },
    { en: "Sleek", fr: "Élégant", type: "Adjective" },
    { en: "Slow", fr: "Lent", type: "Adjective" },
    { en: "Small", fr: "Petit", type: "Adjective" },
    { en: "Smart", fr: "Intelligent", type: "Adjective" },
    { en: "Smooth", fr: "Lisse", type: "Adjective" },
    { en: "Soft", fr: "Mou", type: "Adjective" },
    { en: "Sophisticated", fr: "Sophistiqué", type: "Adjective" },
    { en: "Sour", fr: "Acide", type: "Adjective" },
    { en: "Spacious", fr: "Spacieux", type: "Adjective" },
    { en: "Spicy", fr: "Épicé", type: "Adjective" },
    { en: "Strong", fr: "Fort", type: "Adjective" },
    { en: "Stupid", fr: "Stupide", type: "Adjective" },
    { en: "Sun-drenched", fr: "Baigné de soleil", type: "Adjective" },
    { en: "Sweet", fr: "Sucré", type: "Adjective" },
    { en: "Thick", fr: "Épais", type: "Adjective" },
    { en: "Thin", fr: "Mince", type: "Adjective" },
    { en: "Tired", fr: "Fatigué", type: "Adjective" },
    { en: "Tranquil", fr: "Tranquille", type: "Adjective" },
    { en: "Tree-lined", fr: "Bordé d'arbres", type: "Adjective" },
    { en: "True", fr: "Vrai", type: "Adjective" },
    { en: "Ugly", fr: "Laid", type: "Adjective" },
    { en: "Vibrant", fr: "Vibrant", type: "Adjective" },
    { en: "Warm", fr: "Tiède", type: "Adjective" },
    { en: "Weak", fr: "Faible", type: "Adjective" },
    { en: "Wet", fr: "Mouillé", type: "Adjective" },
    { en: "White", fr: "Blanc", type: "Adjective" },
    { en: "Wide", fr: "Large", type: "Adjective" },
    { en: "Wrong", fr: "Faux", type: "Adjective" },
    { en: "Yellow", fr: "Jaune", type: "Adjective" },
    { en: "Young", fr: "Jeune", type: "Adjective" },

    // --- ADVERBS ---
    { en: "After", fr: "Après", type: "Adverb" },
    { en: "Anywhere", fr: "N'importe où", type: "Adverb" },
    { en: "Before", fr: "Avant", type: "Adverb" },
    { en: "Downstairs", fr: "En bas", type: "Adverb" },
    { en: "Everywhere", fr: "Partout", type: "Adverb" },
    { en: "Here", fr: "Ici", type: "Adverb" },
    { en: "Indoors", fr: "À l'intérieur", type: "Adverb" },
    { en: "Instead", fr: "Plutôt", type: "Adverb" },
    { en: "Later", fr: "Plus tard", type: "Adverb" },
    { en: "Nearby", fr: "Tout près", type: "Adverb" },
    { en: "Normally", fr: "Normalement", type: "Adverb" },
    { en: "Now", fr: "Maintenant", type: "Adverb" },
    { en: "Outdoors", fr: "Dehors", type: "Adverb" },
    { en: "Particularly", fr: "Particulièrement", type: "Adverb" },
    { en: "Possibly", fr: "Possiblement", type: "Adverb" },
    { en: "Sometimes", fr: "Parfois", type: "Adverb" },
    { en: "Somewhere", fr: "Quelque part", type: "Adverb" },
    { en: "Soon", fr: "Bientôt", type: "Adverb" },
    { en: "Still", fr: "Encore", type: "Adverb" },
    { en: "Suddenly", fr: "Soudainement", type: "Adverb" },
    { en: "Then", fr: "Alors", type: "Adverb" },
    { en: "There", fr: "Là", type: "Adverb" },
    { en: "Thus", fr: "Ainsi", type: "Adverb" },
    { en: "Today", fr: "Aujourd'hui", type: "Adverb" },
    { en: "Tomorrow", fr: "Demain", type: "Adverb" },
    { en: "Too", fr: "Trop", type: "Adverb" },
    { en: "Upstairs", fr: "En haut", type: "Adverb" },
    { en: "Usually", fr: "Habituellement", type: "Adverb" },
    { en: "Yesterday", fr: "Hier", type: "Adverb" },
];
